### ISSUE TITLE
django-overwrite-storage on pypi ?

### ISSUE THREAD

**Issue by dotmobo** [ckot/django-overwrite-storage#1]
Hello,

I was looking for a library lighter than django-storage to use the OverwriteStorage and your project is perfectly suited !

Would it be possible to add this library on the pypi repository (https://pypi.python.org/pypi) to ease its installation ?

Thanks you

**Comment by ckot** [comment]
I think the only reason I haven't put this on pypi yet was that I'm not sure my unit tests cover everything needed.  Then again I might have that confused with one of my other packages.  I'm heading out of town in the next hour, so if I forget to do this when I get back, ping me again.

**Comment by madEng84** [comment]
Any news on this?
